# -*- coding: utf-8 -*-
"""RastgeleSAyıTahmini

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HLM6PwLM4nb4ds1gARJezKzQapfEz_Ma
"""
#rastgele sayı tahmin oyunu
import random
sayi= random.randint(1,10)
count=0
kullanici_verisi=0
while(True):
  kullanici_verisi=input("tahmininizi giriniz")
  count+= 1
  if(kullanici_verisi== "çık"):
    print("oyundan çıktınız")
    break
  kullanici_verisi=int(kullanici_verisi)
  if(kullanici_verisi> sayi):
    print("daha küçük bir sayı")
  elif(kullanici_verisi<sayi):
    print("daha büyük bir sayı")
  else:
    print("doğru tahmin ettiniz")